redmine_port: "{{ vault_redmine_port }}"
ansible_user: "{{ vault_ssh_login }}"

db_postgres: "{{ vault_redmine_db_host }}"
db_database: "{{ vault_redmine_db_name }}"
db_username: "{{ vault_redmine_db_username }}"
db_password: "{{ vault_redmine_db_password }}"
db_port: "{{ vault_redmine_db_port }}"
